### ISSUE TITLE
"requirement.txt" missing in the repo?

### ISSUE THREAD

**Issue by Adamliu1** [UCL/COMP0037_22-23#1]
Hi, in the instruction pdf it says there should be a "requirement.txt" file to install required packages for the virtual environment.
However, I couldn't find the corresponding file from the repo. I wonder if the file hasn't been generated for the lab yet.

Thanks!

**Comment by sjulier** [comment]
Thanks. The missing file has been added.

We will also be disabling issues from this repo so that all questions are routed through moodle to put them all in one place.
